GET http://127.0.0.1:8080/api/public/categories

POST http://127.0.0.1:8080/api/public/categories
Content-Type: application/json

{
  
  "categoryName": "Electronics"
}

DELETE http://127.0.0.1:8080/api/public/categories/1

PUT http://127.0.0.1:8080/api/public/categories/3
Content-Type: application/json

{
  "categoryName": "Updated Electronics"
}